"""First migration

Revision ID: 1a810d6ace78
Revises: 
Create Date: 2023-02-10 14:09:51.078332

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1a810d6ace78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
